# Generated by Django 4.1 on 2023-11-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulldetails',
            name='pull_id',
            field=models.IntegerField(),
        ),
    ]
