from account.test.test_account import UserAccountTestCase
from account.test.test_authorization import GitHubAccountTest
from account.test.test_branch import BranchTestCase
from account.test.test_dashboard_fetch import DashBoardFetchTests
from account.test.test_pull_details import PullDetailsTestCase
from account.test.test_repository import RepositoryTestCase
from account.test.test_target_configuration import TargetConfigurationTestCase
from account.test.test_source_configuration import SourceConfigurationTest
